### ISSUE TITLE
Shall the System start a new deployment after files in the repository changed?

### ISSUE THREAD

**Issue by antonxt** [yegor256/thindeck#111]
@yegor256, shall the System close the old Deployment entity and create a new one in case when files in repository were changed during update? As alternative, the System can continue using the old Deployment.

Connected issues: #103, #64.

**Comment by yegor256** [comment]
@davvd pls close this issue, it's fixed already

**Comment by davvd** [comment]
> @davvd pls close this issue, it's fixed already

@yegor256 issue closes as you just asked
