### ISSUE TITLE
Code conventions for requs sources in our project

### ISSUE THREAD

**Issue by antonxt** [yegor256/thindeck#150]
@yegor256, do we need such guidelines? They wound answer to the question: how to write requs code well, taking into account the specifity of our project.

For example, the guidelines can answer these questions:

1. How should we assign numbers to use cases?
2. Should we group use cases by number, e.g., UC10.x are about a user's app that is deployed in thindeck, UC9.x are the cases of anonymous user, etc.
3. How do we split the code into separate files?
4. What tab characters we must use, and other low-level sources requirements to pass code analyzer policies durung automated build.
5. Where and in what order should we define use cases and types?
6. Do we have to define exceptions right after the use case?

These guidelines can be implemented in a separate guidelines.req containing vision artifact, or a readme file.

**Comment by yegor256** [comment]
@antonxt  SRS is removed from the project, we won't continue in this ticket
