### ISSUE TITLE
Travis downloads more than 1500 lib files during each build

### ISSUE THREAD

**Issue by antonxt** [yegor256/thindeck#189]
For some reason, Travis makes a lot of downloads each time. Build log contains more than 1500 lines like:

```
[INFO] Downloading: https://oss.sonatype.org/content/groups/public/org/apache/maven/scm/maven-scm-provider-svnexe/1.8/maven-scm-provider-svnexe-1.8.jar
```

See the full example [here](https://travis-ci.org/yegor256/thindeck/builds/26782363).

Besides of consuming a lot of traffic and taking some time to build, the process fails from time to time ([see the example](https://travis-ci.org/yegor256/thindeck/builds/26782363)), when Travis fails to download one of the lib because of the connection problem.

Maybe we can optimize this somehow, to avoid these downloads each time? When I build locally, the libs are downloaded once, later they are  reused.

**Comment by tyrcho** [comment]
This seems to have done the trick for me : https://github.com/HearthStats/HearthStats.net-Uploader/commit/59a62f6ed70a5b7c60f1a4cc1230d9227457aa52 , should probably work in your project too.

**Comment by longtimeago** [comment]
@tyrcho Thanks for the hint. We did this some time ago
