### ISSUE TITLE
[UC1] cobertura mandatory coverage of 80%

### ISSUE THREAD

**Issue by yegor256** [yegor256/thindeck#289]
Let's use Cobertura (as part of Qulice) to control the overall code coverage. Let's make sure that the minimum we have is 80%

**Comment by 0pdd** [comment]
@yegor256 the puzzle [#580](https://github.com/yegor256/thindeck/issues/580) is still not solved; solved: [#319](https://github.com/yegor256/thindeck/issues/319), [#351](https://github.com/yegor256/thindeck/issues/351), [#554](https://github.com/yegor256/thindeck/issues/554), [#unknown](), [#unknown]().

**Comment by 0pdd** [comment]
@yegor256 all 6 puzzles are solved here: [#319](https://github.com/yegor256/thindeck/issues/319), [#351](https://github.com/yegor256/thindeck/issues/351), [#554](https://github.com/yegor256/thindeck/issues/554), [#580](https://github.com/yegor256/thindeck/issues/580), [#unknown](), [#unknown]().
