### ISSUE TITLE
[UC1] add repository

### ISSUE THREAD

**Issue by yegor256** [yegor256/thindeck#290]
Let's implement repository adding functionality. A user should be able to enter repository name and URI and click "add". We should create a new repo and save its URI into memo. I think, it should go right into:

``` xml
<memo>
  <uri>...</uri>
</memo>
```

**Comment by davvd** [comment]
@yegor256 last 9 puzzles `462-c5de49b4`/#539, `462-ec070d26`/#538, `464-b7102912`/#474, `420-427af42c`/#471, `409-272f0225`/#537, `408-195c40b4`/#535, `408-b5d67474`/#533, `408-75ca2bde`/#534, `410-108e5987`/#520 that originated from here were solved
