### ISSUE TITLE
[UC2] ReadConfig step

### ISSUE THREAD

**Issue by yegor256** [yegor256/thindeck#291]
Let's create a new step `ReadConfig` which should read `.thindeck.yml` file from the root directory of the repository, parse it (YAML), and update memo. Let's make this configuration options possible:

``` yaml
domains: ["example.com", "test.example.com"]
ports: [80, 443]
```

They should be mapped to:

``` xml
<memo>
  <domains>
    <domain>example.com</domain>
    <domain>test.example.com</domain>
  </domains>
  <ports>
    <port>80</port>
    <port>443</port>
  </ports>
</memo>
```

**Comment by davvd** [comment]
the last puzzle `369-8972f543`/#452 solved
