### ISSUE TITLE
pom.xml:480-481: Increase test code coverage >=...

### ISSUE THREAD

**Issue by davvd** [yegor256/thindeck#319]
Puzzle `289-341cbc3a` in `pom.xml:480-481` has to be resolved: Increase test code coverage >= 80% for all packages and uncomment lines below.

**Comment by 0pdd** [comment]
@davvd the puzzle [#580](https://github.com/yegor256/thindeck/issues/580) is still not solved; solved: [#351](https://github.com/yegor256/thindeck/issues/351), [#554](https://github.com/yegor256/thindeck/issues/554), [#unknown](), [#unknown]().

**Comment by 0pdd** [comment]
@davvd all 5 puzzles are solved here: [#351](https://github.com/yegor256/thindeck/issues/351), [#554](https://github.com/yegor256/thindeck/issues/554), [#580](https://github.com/yegor256/thindeck/issues/580), [#unknown](), [#unknown]().
