### ISSUE TITLE
Nginx.java:69-72: When a *hosts.conf file is...

### ISSUE THREAD

**Issue by davvd** [yegor256/thindeck#393]
Puzzle `345-7e2a1db1` in `src/main/java/com/thindeck/steps/Nginx.java:69-72` has to be resolved: When a *hosts.conf file is created for a new host, it should be included in nginx.conf so that it can be loaded by the Nginx server. See the explanation in in https://github.com/yegor256/thindeck/issues/347 for more details.

**Comment by carlosmiranda** [comment]
@davvd @yegor256 I know this task is old, but it looks like I wasn't paid for it. Pull request was in #402...
