### ISSUE TITLE
In SRS server creation and deletion are called every time on application launch

### ISSUE THREAD

**Issue by andrewbol** [yegor256/thindeck#399]
UC2.3 contains creation and deletion of a server as the first and the last steps. This use case is called from UC2 where a repository launches an application. It seems that a server should not be created and deleted every time on launching application because in this case the repository will not even exist.

**Comment by davvd** [comment]
@yegor256 dispatch this issue please

**Comment by yegor256** [comment]
@andrewbol SRS is removed from the project for now, thanks for the ticket anyway
