### ISSUE TITLE
Implement UC4: Use Case where User reads...

### ISSUE THREAD

**Issue by davvd** [yegor256/thindeck#4]
Use Case where User reads deployment logs using Repository...

Full description of the Use Case is here http://doc.thindeck.com/requs/requs.xml#UC4

The following table describes all technical details of Use Case `UC4`:

<table> <thead> <tr> <th>Property</th> <th>Details</th> </tr> </thead> <tbody> <tr> <td>ID</td> <td>UC4</td> </tr> <tr> <td>Signature</td> <td>_self

reads deployment logs using

repo</td> </tr> <tr> <td>Primary</td> <td>User</td> </tr> <tr> <td>Actors</td> <td>repo

as Repository;

deployments

as Deployment</td> </tr> <tr> <td>Success Flow</td> <td>1.

system

lists

deployments

2.

system

"displays a list of deployments that has already been executed"

3.

user

"chooses a deployment and initiates viewing its log"

4.

system

"displays a log for the chosen deployment"</td> </tr> </tbody>
</table>

Actors taking participation in the Use Case have the following properties:

<table>
   <thead>
      <tr>
         <th>Actor</th>
         <th>Properties</th>
      </tr>
   </thead>
   <tbody>
      <tr>
         <td>User</td>
         <td>"a person who uses or wants to use hosting and is identified by the system (logged in)"

 * repo : Repository
 * URN : "a unique identifier of itself, for example
  urn:github:526301"
 * authTokens : "a list of auth tokens to each auth
  provider the user connected to, e.g., Google, Facebook,
  etc."
 * balance : "amount of money available, can be stored
  as integer number of cents"</td>
      </tr>
      <tr>
         <td>Repository</td>
         <td>"a local copy of files and folders being pulled every 5 minutes from some remote source"

 * name : "a unique name of the repo in user's
  account"
 * deployment : Deployment
 * dockerFile : DockerFile
 * manifest : Manifest</td>
      </tr>
      <tr>
         <td>Deployment</td>
         <td>"a summary statistics of Containers related to a Repository, with their statuses and text logs"

 * container : Container
 * state : "one from the list: building, running"
 * hourlyUsage : HourlyUsage</td>
      </tr>
   </tbody>
</table>

**Comment by yegor256** [comment]
@davvd  SRS is removed from the project, we won't continue in this ticket
