### ISSUE TITLE
DyTasks.java:47-47: Implement all and add methods....

### ISSUE THREAD

**Issue by davvd** [yegor256/thindeck#404]
Puzzle `373-400c0a90` in `src/main/java/com/thindeck/dynamo/DyTasks.java:47-47` has to be resolved: Implement all and add methods.

If you have any technical questions, don't ask me, submit new tickets instead

**Comment by davvd** [comment]
@php-coder please don't touch this task, someone else will pick it up, thanks

**Comment by davvd** [comment]
@oruam85 could you please pick this up? This [article](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) explains how we work. Any technical questions you may ask right here... **30 mins** is the budget of the task. This is exactly how much will be paid when the problem is [solved](http://www.xdsd.org/2014/04/15/definition-of-done.html) (no matter how much time you will actually spend). See [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for more information

**Comment by oruam85** [comment]
@davvd add() method is already implemented and all method was implemented by @php-coder in this pending PR https://github.com/php-coder/thindeck/commit/3bcaea02b390da931df2de0f5d84bd683d5d6909.

But the class DyTasksTest has not the test of the add and all methods. Do you want that i do this tests?

**Comment by yegor256** [comment]
@oruam85 yes, please. until pull request is merged, it doesn't count

**Comment by oruam85** [comment]
@davvd merged

**Comment by oruam85** [comment]
@davvd @yegor256 this bug is already merged.

**Comment by davvd** [comment]
@oruam85 you're working with this issue for 10 days already... as a reminder, don't forget to remove the `@todo` puzzle from the source code... -30 added to your rating, at the moment it is: +60

**Comment by oruam85** [comment]
@davvd  Why? this bug was merged an ready for to close days ago. Check the message above please.

**Comment by oruam85** [comment]
@davvd check the messages above. this bug was merged before that your message about penalties

**Comment by davvd** [comment]
@oruam85 it's not yours any more,because it took too long,please stop working with it. -60 added to your rating, current score is: +60

**Comment by oruam85** [comment]
@davvd  really? @yegor256 Please review the message above. I am waiting for close this bug and the only answer of this person was penalties!!!!! what is this?

**Comment by oruam85** [comment]
@davvd I waited six days to close the bug and instead only respond by penalties.

**Comment by oruam85** [comment]
@davvd @yegor256 It does not seem fair that this should be penalized. I want my rating points back and pay for resolving the bug in time !!

**Comment by yegor256** [comment]
@davvd please, assign @oruam85 back to this issue

**Comment by davvd** [comment]
@pinaf This task is yours, please go ahead keeping in mind [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). If any questions, don't hesitate to ask right here. Task's budget is **30 mins** (see [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for explanation)

**Comment by pinaf** [comment]
@davvd I'm confused. Didn't @oruam85 finish the task already? The 2 bug reports he created were also assigned to other people so what is there to be done?

**Comment by yegor256** [comment]
@pinaf yes, right, this task is for @oruam85 Don't touch it please, it will be re-assigned soon

**Comment by pinaf** [comment]
@yegor256 @davvd thank you for the feedback.

**Comment by davvd** [comment]
> @davvd please, assign @oruam85 back to this issue

@yegor256 of course! @oruam85 it's your ticket now, please go ahead

**Comment by oruam85** [comment]
@davvd this bug was resolved days ago. Please close it

**Comment by oruam85** [comment]
@davvd please close this bug. The code was merged 5 days ago.

**Comment by oruam85** [comment]
@davvd Please close this bug.

**Comment by davvd** [comment]
The task is closed, thanks everybody

**Comment by davvd** [comment]
@oruam85 I just added **30 mins** to your account, many thanks for your contribution..

+30 added to your rating, at the moment it is: +90
