### ISSUE TITLE
DyUser.java:51-53: Implement usage method. To do...

### ISSUE THREAD

**Issue by davvd** [yegor256/thindeck#408]
Puzzle `374-a01072dc` in `src/main/java/com/thindeck/dynamo/DyUser.java:51-53` has to be resolved: Implement usage method. To do this we need to implement a class DyUsage that implements the Usage interface. This will obtain the usage associated to this user from Dynamo DB.

If you have any technical questions, don't ask me, submit new tickets instead

**Comment by davvd** [comment]
@flexelem you're working with this ticket for the last 7 days. If it's not closed within the next 48 hours, it will be re-assigned to someone else, see [No Obligations](http://www.xdsd.org/2014/04/13/no-obligations-principle.html) principle... -5 added to your rating, current score is: -5

**Comment by davvd** [comment]
@flexelem the task is overdue, and I have to re-assign it to someone else. Please, stop working with it immediately. In general, we're against overdue tasks, check [this page](http://www.xdsd.org/2014/04/13/no-obligations-principle.html). -60 to your rating, your total score is -65

**Comment by davvd** [comment]
@wb14123 the task is for you now, follow [these guidelines](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). Don't hesitate to ask any technical questions right here. Task's budget is **30 mins** (see [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for explanation)

**Comment by davvd** [comment]
@wb14123 the ticket is with you for 15 days already. If it's not finished in the next 48 hours, it will be re-assigned to someone else, see [No Obligations](http://www.xdsd.org/2014/04/13/no-obligations-principle.html) principle, [this article](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html) should help if you're stuck... as a reminder, don't forget to remove the `@todo` puzzle from the source code... added -30 to your rating, now it is equal to -135

**Comment by davvd** [comment]
@wb14123 it takes too long. Usually, we expect any task to be finished in less than a week. I'll assign someone else. Please stop working with it right now. See our [no obligations](http://www.xdsd.org/2014/04/13/no-obligations-principle.html) principle. -60 added to your rating, current score is: -405

**Comment by davvd** [comment]
@carlosmiranda it's yours,please go ahead

**Comment by carlosmiranda** [comment]
@davvd Waiting for #523 (pull request).

**Comment by carlosmiranda** [comment]
@davvd We're waiting for #523.

**Comment by davvd** [comment]
> @davvd Waiting for #523 (pull request).

@carlosmiranda yes, waiting for #523

**Comment by davvd** [comment]
> @davvd We're waiting for #523.

@carlosmiranda yes, of course, we'll wait for #523

**Comment by davvd** [comment]
#523 is closed, it was an impediment

**Comment by davvd** [comment]
these 3 puzzles were created in this ticket: `408-195c40b4`, `408-b5d67474`, `408-75ca2bde`

**Comment by davvd** [comment]
Thanks all, I am closing

**Comment by davvd** [comment]
@carlosmiranda Thanks for your contribution, **30 mins** was added to your account, payment ID is `53354577`... added +30 to your rating, now it is equal to [+3703](http://www.netbout.com/b/35023?open=rating)

**Comment by davvd** [comment]
@yegor256 last 3 puzzles originated from here are solved: `408-195c40b4`/#535, `408-b5d67474`/#533, `408-75ca2bde`/#534
