### ISSUE TITLE
DyUser.java:44-50: At the moment, the repos()...

### ISSUE THREAD

**Issue by davvd** [yegor256/thindeck#409]
Puzzle `374-bb504035` in `src/main/java/com/thindeck/dynamo/DyUser.java:44-50` has to be resolved: At the moment, the repos() method returns all Repos associated with the Dynamo region, and this is definitely incorrect. I think we need to refactor DyRepos in order to include a user criteria (probably URN) in its constructor, and have DyUser pass it so that it will only return the associated criteria. I'm not completely sure about this design, feel free to implement something else if you think it's wrong. The intuition behind it is that we should only get the repos associated with the current user.

If you have any technical questions, don't ask me, submit new tickets instead

**Comment by davvd** [comment]
@cyberone check this ["no obligations principle"](http://www.xdsd.org/2014/04/13/no-obligations-principle.html).. This task is on your name for at least 7 days. If you can't close it within the next 48 hours I'll have to assign someone else to it

**Comment by davvd** [comment]
@cyberone this task is taking too long, I have to change the performer, sorry. Please stop working with it right now. See our [no obligations](http://www.xdsd.org/2014/04/13/no-obligations-principle.html) principle

-60 to your rating, your total score is [-40](http://www.netbout.com/b/35076?open=rating)

**Comment by davvd** [comment]
@wb14123 the task is for you now, follow [these guidelines](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). Don't hesitate to ask any technical questions right here

Total fixed cost of this task is **30 mins** (see [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for more info)

**Comment by wb14123** [comment]
If DyRepos include a user criteria, how to construct it in `DyBase.repos()`? In my understand, `DyBase.repos()` should return all users' repos. I think I could return all repos in DyRepos while user criteria is null, is that OK?

**Comment by yegor256** [comment]
@wb14123 we never use NULL anywhere, see http://www.yegor256.com/2014/05/13/why-null-is-bad.html

**Comment by davvd** [comment]
@wb14123 the ticket is with you for 11 days already. If it's not finished in the next 48 hours, it will be re-assigned to someone else, see [No Obligations](http://www.xdsd.org/2014/04/13/no-obligations-principle.html) principle, [this article](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html) should help if you're stuck; do not forget to remove the TODO puzzle from the source code; -30 to your rating, your total score is +45

**Comment by davvd** [comment]
@wb14123 the task is overdue, and I have to re-assign it to someone else. Please, stop working with it immediately. In general, we're against overdue tasks, check [this page](http://www.xdsd.org/2014/04/13/no-obligations-principle.html). added -60 to your rating, now it is equal to -75

**Comment by davvd** [comment]
@carlosmiranda it's yours,please go ahead

**Comment by carlosmiranda** [comment]
@davvd We're waiting for #524.

**Comment by davvd** [comment]
> @davvd We're waiting for #524.

@carlosmiranda yep, got it, let's wait for #524 being solved

**Comment by davvd** [comment]
we were waiting for #524 - it is closed already

**Comment by carlosmiranda** [comment]
@davvd we're waiting for #528 now (pull request).

**Comment by davvd** [comment]
> @davvd we're waiting for #528 now (pull request).

@carlosmiranda OK, let's wait for #528

**Comment by davvd** [comment]
we were waiting for #528 - it is closed already

**Comment by davvd** [comment]
there is a puzzle in this code `409-272f0225`, we'll resolve it later

**Comment by davvd** [comment]
Finished, thanks, closing..

**Comment by davvd** [comment]
@carlosmiranda **30 mins** added to your account (payment number `54118997`), many thanks for your contribution!... +30 added to your rating, at the moment it is: [+4096](http://www.netbout.com/b/35023?open=rating)

**Comment by davvd** [comment]
@yegor256 the last puzzle `409-272f0225`/#537 solved
