### ISSUE TITLE
DyUserTest.java:52-54: We should create an integration...

### ISSUE THREAD

**Issue by davvd** [yegor256/thindeck#410]
Puzzle `374-c45270af` in `src/test/java/com/thindeck/dynamo/DyUserTest.java:52-54` has to be resolved: We should create an integration test for DyUser. Let's call it DyUserITCase. It should test whether DyUser can perform its operations on a real (local) Dynamo server. When done, ensure that this puzzle is removed.

If you have any technical questions, don't ask me, submit new tickets instead

**Comment by adko-pl** [comment]
@davvd Changes have been delivered in https://github.com/yegor256/thindeck/pull/517

**Comment by davvd** [comment]
@adko-pl this task is not yours any more (took too long),please stop. I'll give you something else

added -60 to your rating, now it is equal to +60

**Comment by adko-pl** [comment]
@davvd the changes for this task have been merged, 9hours ago

**Comment by adko-pl** [comment]
@davvd besides, my previous rating was 125, not 120, https://github.com/jcabi/jcabi-s3/issues/16#issuecomment-71628410

**Comment by yegor256** [comment]
@adko-pl please create an account in www.netbout.com and send me your name there. I will share your rating stats

**Comment by yegor256** [comment]
@davvd please assign @adko-pl back to this task

**Comment by yegor256** [comment]
@adko-pl as you see, the task was assigned to you on the 22nd of Dec and today is 13th of Feb. That's way over 10 days. so, we'll make an exception now, but for the future, keep this rule in mind: http://www.teamed.io/policy.html#7

**Comment by adko-pl** [comment]
@yegor256 thanks Yegor, I will keep the 10 days rule in mind.

**Comment by adko-pl** [comment]
@yegor256 my netbout.com alias is "@adamsiemion"

**Comment by davvd** [comment]
the code made here contains a puzzle `410-108e5987`, which will be resolved soon

**Comment by davvd** [comment]
@carlosmiranda please go ahead with this task, it's yours

**Comment by carlosmiranda** [comment]
PR #522.

**Comment by carlosmiranda** [comment]
@davvd waiting for #522.

**Comment by davvd** [comment]
> @davvd waiting for #522.

@carlosmiranda got it, let's wait for #522

**Comment by davvd** [comment]
impediment in issue #522 is closed, we can probably try to continue here

**Comment by carlosmiranda** [comment]
@davvd Close this already please.

**Comment by davvd** [comment]
> @davvd Close this already please.

@carlosmiranda the ticket will be closed when the puzzle is removed from the code, keep in mind that it takes some time after deployment to update our statistics, please give me at least a day

**Comment by carlosmiranda** [comment]
@davvd puzzle was removed in #522, please close it.

**Comment by davvd** [comment]
> @davvd puzzle was removed in #522, please close it.

@carlosmiranda the ticket will be closed when the puzzle is removed from the code, keep in mind that it takes some time after deployment to update our statistics, please give me at least a day

**Comment by davvd** [comment]
@carlosmiranda thanks, paid, **30 mins** to your account, payment ID is `53325078`. +30 added to your rating, at the moment it is: [+3688](http://www.netbout.com/b/35023?open=rating)

**Comment by davvd** [comment]
I am closing it, thanks all

**Comment by adko-pl** [comment]
@davvd my changes delivered for this task have been consumed, will I get payment for them?

**Comment by yegor256** [comment]
@davvd please add extra 30 mins to @adko-pl

**Comment by yegor256** [comment]
@adko-pl you understand that it was totally your mistake here? you didn't remove the puzzle from the source code, that's why the task was not closed after your pull request. making an exception now. keep this in mind for the future: http://www.teamed.io/policy.html#7

**Comment by adko-pl** [comment]
@yegor256 Yes, I understand my mistake. Thank you for help and understanding the situation.

**Comment by davvd** [comment]
> @davvd please add extra 30 mins to @adko-pl 

@yegor256 I've paid 30 mins to @adko-pl in transaction `AP-83N466368E692972R`

**Comment by davvd** [comment]
@yegor256 the last puzzle `410-108e5987`/#520 originated from here solved
