### ISSUE TITLE
DyTasks.java:50-50: Implement open method....

### ISSUE THREAD

**Issue by davvd** [yegor256/thindeck#421]
Puzzle `406-b5fe8676` in `src/main/java/com/thindeck/dynamo/DyTasks.java:50-50` has to be resolved: Implement open method.

If you have any technical questions, don't ask me, submit new tickets instead

**Comment by davvd** [comment]
@adko-pl it's not yours any more,because it took too long,please stop working with it; -60 added to your rating, current score is: [+0](http://www.netbout.com/b/35150?open=rating)

**Comment by davvd** [comment]
@carlosmiranda it's yours, please go ahead

**Comment by carlosmiranda** [comment]
@davvd We're waiting for #523.

**Comment by davvd** [comment]
> @davvd We're waiting for #523.

@carlosmiranda yes, of course, we'll wait for #523

**Comment by davvd** [comment]
we were waiting for #523 - it is closed already

**Comment by carlosmiranda** [comment]
@davvd My apologies, we are waiting for #524.

**Comment by davvd** [comment]
> @davvd My apologies, we are waiting for #524.

@carlosmiranda got it, let's wait for #524

**Comment by davvd** [comment]
FYI, issue #524 is already closed, and we were waiting for it..

**Comment by carlosmiranda** [comment]
@davvd We're waiting for #531 now (pull request).

**Comment by davvd** [comment]
> @davvd We're waiting for #531 now (pull request).

@carlosmiranda yes, waiting for #531

**Comment by davvd** [comment]
#531 is closed, we were waiting for it.. maybe we can continue?

**Comment by davvd** [comment]
Done, thanks all, closing..

**Comment by davvd** [comment]
@carlosmiranda thanks, paid, **30 mins** to your account, payment ID is `54253543`, task took 27 hours and 32 mins to complete. +30 added to your rating, at the moment it is: [+4468](http://www.netbout.com/b/35023?open=rating)
