### ISSUE TITLE
VerboseProcess in NginxTest.reloadsConfiguration

### ISSUE THREAD

**Issue by yegor256** [yegor256/thindeck#445]
let's use `VerboseProcess` from jcabi-log in `NginxTest.reloadsConfiguration`. the test will be shorter and more readable

**Comment by davvd** [comment]
@oruam85 this ticket is yours now, please proceed, and keep in mind [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). Any technical questions you should ask right here... The cost of this task is **30 mins** (this is exactly how much will be paid, not less not more), when the task is [done](http://www.xdsd.org/2014/04/15/definition-of-done.html)

**Comment by oruam85** [comment]
@davvd this ticket is open yet? i can read that @php-coder did  a pull request days ago #457

**Comment by yegor256** [comment]
@oruam85 that's right, it's fixed already

**Comment by davvd** [comment]
@oruam85 Thank you, I've added **30 mins** to your account in payment/transaction "`49914208`". +30 added to your rating, at the moment it is: +90
