### ISSUE TITLE
com.thindeck.dynamo classes should be annotated with @EqualsAndHashCode

### ISSUE THREAD

**Issue by carlosmiranda** [yegor256/thindeck#460]
I noticed that the following classes are marked with Lombok's `@EqualsAndHashCode` annotation:
- DyTask
- DyTasks

However the following classes are _not_ annotated with `@EqualsAndHashCode`:
- DyBase
- DyRepo
- DyRepos
- DyUser

For consistency's sake, we should have Lombok generate `@EqualsAndHashCode` for all of these classes. Otherwise they will simply inherit from `java.lang.Object` which is not the best practice.

**Comment by 0pdd** [comment]
@carlosmiranda the only puzzle [#555](https://github.com/yegor256/thindeck/issues/555) is solved here.
