### ISSUE TITLE
DyTxn.java:60-60: increment should use actions fetched...

### ISSUE THREAD

**Issue by davvd** [yegor256/thindeck#462]
Puzzle `372-437563d3` in `src/main/java/com/thindeck/dynamo/DyTxn.java:60-60` has to be resolved: increment should use actions fetched from item.

If you have any technical questions, don't ask me, submit new tickets instead

**Comment by davvd** [comment]
@cyberone the task is overdue, and I have to re-assign it to someone else. Please, stop working with it immediately. In general, we're against overdue tasks, check [this page](http://www.xdsd.org/2014/04/13/no-obligations-principle.html)

**Comment by davvd** [comment]
@pandreev This task is yours, please go ahead keeping in mind [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). If any questions, don't hesitate to ask right here

This task's budget is **30 mins**. This is exactly how much will be paid when the problem explained above is solved. See [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for more information

**Comment by davvd** [comment]
@pandreev the ticket is with you for 10 days already. If it's not finished in the next 48 hours, it will be re-assigned to someone else, see [No Obligations](http://www.xdsd.org/2014/04/13/no-obligations-principle.html) principle. do not forget to remove the TODO puzzle from the source code. added -30 to your rating, now it is equal to -60

**Comment by davvd** [comment]
@pandreev the task is overdue, and I have to re-assign it to someone else. Please, stop working with it immediately. In general, we're against overdue tasks, check [this page](http://www.xdsd.org/2014/04/13/no-obligations-principle.html). added -60 to your rating, now it is equal to -150

**Comment by davvd** [comment]
@oruam85 the task is yours, please go ahead

**Comment by oruam85** [comment]
@davvd  The PR is https://github.com/yegor256/thindeck/pull/510

**Comment by oruam85** [comment]
@davvd we needs more time here

**Comment by davvd** [comment]
> @davvd we needs more time here

@oruam85 agreed, take your time

**Comment by oruam85** [comment]
@davvd merged, please close this bug

**Comment by davvd** [comment]
@yegor256 these 2 puzzles were created in this ticket: `462-c5de49b4`, `462-ec070d26`/#538

**Comment by davvd** [comment]
@yegor256 Thanks, closed

**Comment by davvd** [comment]
@oruam85 **30 mins** was added to your account, many thanks for your contribution! The task took 57307596.... +30 added to your rating, current score is: +30

**Comment by davvd** [comment]
@yegor256 Last 2 puzzles came from here were resolved: `462-c5de49b4`/#539, `462-ec070d26`/#538
