### ISSUE TITLE
Mvn running ImmutabilityTest

### ISSUE THREAD

**Issue by piotrkot** [yegor256/thindeck#469]
In IDE (IntelliJ in my case) ImmutabilityTest fails when a class DyBase is not marked Immutable. This is right as it is expected.
By running `mvn clean install -Pqulice` I expect all tests should be run, as well. From the logs I see ImmutabilityTest is run, too. However, this test runs successfully even though a class DyBase is not marked Immutable.

**Comment by davvd** [comment]
@oruam85 this task is for you, keep [these principles](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) in mind, and don't hesitate to ask any technical questions

The budget of this issue is **30 mins**, which is exactly how much will be paid when the task is *done* (see [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for explanation)

**Comment by oruam85** [comment]
@davvd can you find somebody else for this bug?

**Comment by davvd** [comment]
> @davvd can you find somebody else for this bug?

@oruam85 someone else will help in this task, no problem at all

**Comment by davvd** [comment]
@maxim-kornienko could you please pick this up? This [article](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) explains how we work. Any technical questions you may ask right here... This task's budget is **30 mins**. This is exactly how much will be paid when the problem explained above is solved. See [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for more information

**Comment by maxim-kornienko** [comment]
@piotrkot the problem was that as maven runs tests in forked process the classpath was wrong. 
There are two possible solutions:
* Run maven with `-DforkCount=0` (just FYI)
* Fix classloaders issue in `ClasspathRule.allTypes()` (done in pull request #513)

@davvd Check pull request #513

**Comment by davvd** [comment]
@maxim-kornienko you're working with this issue for 15 days already... -30 added to your rating, at the moment it is: +75

**Comment by maxim-kornienko** [comment]
@davvd camooooooon, it's already merged. 
@yegor256 I think algorithm of comments generation should be improved to be triggered by merge of pull request. Of course no penalties should happen after it.

**Comment by yegor256** [comment]
@maxim-kornienko the task is not only about pull request merging, but about closing the task. The task is still open, as you see.

**Comment by maxim-kornienko** [comment]
@piotrkot everything is fixed, let's close the task.

**Comment by maxim-kornienko** [comment]
@yegor256 so why not penaltizing task owner then?

**Comment by yegor256** [comment]
@maxim-kornienko :) because it's your responsibility to chase the task owner and make sure he/she closes the task, check this article: http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html

**Comment by maxim-kornienko** [comment]
@yegor256 I think this article is closer related to the discussion topic http://www.yegor256.com/2014/04/20/how-hourly-rate-is-calculated.html :) 
BTW If task is not closed by the owner in time can I submit an issue about that?

**Comment by piotrkot** [comment]
@maxim-kornienko Indeed, I was missing explicit request for closing the task. Thanks. Closing it now.

**Comment by yegor256** [comment]
@maxim-kornienko if you see a delay in response from the task reporter, complain to the project manager first. Then, to the architect (myself, in this case). But do something. You're the only one who is interested in closing the task.

**Comment by davvd** [comment]
@maxim-kornienko thanks, paid, **30 mins** to your account, payment ID is `51247685`

+30 added to your rating, at the moment it is: +135
