### ISSUE TITLE
DyMemo.java:47-47: implement update....

### ISSUE THREAD

**Issue by davvd** [yegor256/thindeck#470]
Puzzle `405-d6ee4a6b` in `src/main/java/com/thindeck/dynamo/DyMemo.java:47-47` has to be resolved: implement update.

If you have any technical questions, don't ask me, submit new tickets instead

**Comment by adko-pl** [comment]
@davvd delivered the changes in https://github.com/yegor256/thindeck/pull/516

**Comment by adko-pl** [comment]
@davvd changes have been merged

**Comment by davvd** [comment]
Closed, thanks all

**Comment by davvd** [comment]
@adko-pl Thank you, I've added **30 mins** to your account in payment/transaction "`AP-0FD82617TB659913Y`". added +30 to your rating, now it is equal to [+30](http://www.netbout.com/b/35150?open=rating)
