### ISSUE TITLE
DyScenario.java:42-42: Implement steps method - example...

### ISSUE THREAD

**Issue by davvd** [yegor256/thindeck#471]
Puzzle `420-427af42c` in `src/main/java/com/thindeck/dynamo/DyScenario.java:42-42` has to be resolved: Implement steps method - example in OnDeploy. Task command will determine steps.

If you have any technical questions, don't ask me, submit new tickets instead

**Comment by davvd** [comment]
@alexdag you're working with this ticket for the last 12 days. If it's not closed within the next 40 hours, it will be re-assigned to someone else, see [No Obligations](http://www.xdsd.org/2014/04/13/no-obligations-principle.html) principle. do not forget that you should remove the `@todo` puzzle from the source code. -30 added to your rating, current score is: [-60](http://www.netbout.com/b/35099?open=rating)

**Comment by AlexDag** [comment]
@davvd sorry for my delay to start this job.Please, give me some time again. I.m starting now.thanks

**Comment by yegor256** [comment]
@davvd looks like we need a bit more time here

**Comment by AlexDag** [comment]
I've created PR for this job

**Comment by davvd** [comment]
> @davvd looks like we need a bit more time here

@yegor256 of course, thanks for letting me know, take your time

**Comment by davvd** [comment]
@carlosmiranda the task is yours please proceed

**Comment by carlosmiranda** [comment]
@davvd Please assign someone else.

**Comment by carlosmiranda** [comment]
@davvd @yegor256 Please assign someone else to this already. This task is blocking my task allocations.

**Comment by davvd** [comment]
> @davvd Please assign someone else.

@carlosmiranda I will try to find someone else

**Comment by davvd** [comment]
> @davvd @yegor256 Please assign someone else to this already. This task is blocking my task allocations.

@carlosmiranda OK, I will try to assign someone else

**Comment by davvd** [comment]
@yegor256 Thanks, closing it now.
