### ISSUE TITLE
SRS mentions dockerFile though using exactly Docker is not required

### ISSUE THREAD

**Issue by andrewbol** [yegor256/thindeck#483]
Repository contains a dockerFile though using exactly Docker is required nowhere in the SRS.

More over it is not completely clear how to prepare a repository to run an application from it, what repository contents must be and how this must be defined in a configuration.

**Comment by davvd** [comment]
@yegor256 please pay attention to this issue

**Comment by yegor256** [comment]
@andrewbol SRS is removed from the project for now, thanks for the ticket anyway
