### ISSUE TITLE
Update the Copyright year

### ISSUE THREAD

**Issue by oruam85** [yegor256/thindeck#489]
In the license.txt file the Copyright year should be 2015.

The project has 100+ other occurences of "2014" in copyright context

**Comment by davvd** [comment]
@marczeeee please pick this up, and keep in mind [these instructions](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). Any technical questions - ask right here... Task's budget is **30 mins** (see [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for explanation)

**Comment by Marczeeee** [comment]
@oruam85 Related pull request #499 was merged. Please close the issue.

**Comment by oruam85** [comment]
@Marczeeee Thank you. Closed

**Comment by davvd** [comment]
@marczeeee **30 mins** was added to your account, many thanks for your contribution!... +30 added to your rating, at the moment it is: +150
