### ISSUE TITLE
Use DyRepos.get to check if the repo exist in DyRepos

### ISSUE THREAD

**Issue by wb14123** [yegor256/thindeck#494]
In [DyRepos.java](https://github.com/yegor256/thindeck/blob/master/src%2Fmain%2Fjava%2Fcom%2Fthindeck%2Fdynamo%2FDyRepos.java), `add` first check if the repo exist, then add it. But the logic of check is the same as it is written in `get`, so why not use `get` to check it in order to not repeat yourself?

**Comment by yegor256** [comment]
@wb14123 I agree that there is code duplication in this class, you're right. But I think we need to move this duplicated code into a supplementary private method.

**Comment by davvd** [comment]
I'll find a developer for the task soon...

**Comment by davvd** [comment]
@wb14123 thanks a lot for reporting, **15 mins** added to your acc, pmt ID `AP-24772412U2256303H`

**Comment by davvd** [comment]
@wentwog the task is yours, please go ahead

**Comment by wentwog** [comment]
PR #505

**Comment by wentwog** [comment]
@davvd the PL is merged, could you close the ticket ?

**Comment by yegor256** [comment]
@wentwog ask @wb14123 to close it, he is the reporter

**Comment by davvd** [comment]
@wentwog thanks, paid, **30 mins** to your account, payment ID is `50570715`; +30 to your rating, your total score is [+80](http://www.netbout.com/b/35104?open=rating)
