### ISSUE TITLE
#471- DyScenario - Step implementation #497

### ISSUE THREAD

**Issue by AlexDag** [yegor256/thindeck#498]
"DyScenario steps should depend on DyTask (which creates the scenario), not just a constant list of steps" #497  
 It is difference from this job definition :
"#420:30min Implement steps method - example in OnDeploy.
 *  Task command will determine steps"

**Comment by davvd** [comment]
@yegor256 dispatch this issue please

**Comment by yegor256** [comment]
@AlexDag this class is gone, thanks for the ticket anyway
