### ISSUE TITLE
Broken link for logo image in technical documentation homepageo

### ISSUE THREAD

**Issue by FrancescoBianchi** [yegor256/thindeck#501]
![brokenlogolink](https://cloud.githubusercontent.com/assets/8255063/5791027/52d6df96-9eae-11e4-894a-73fadb13c09b.PNG)

**Comment by FrancescoBianchi** [comment]
Duplicates #481

**Comment by yegor256** [comment]
@rultor release, tag is `0.4.6`

**Comment by yegor256** [comment]
@FrancescoBianchi thanks for reporting, I'll fix it now by a new release
