### ISSUE TITLE
Review design of com.thindeck.api.Step interface

### ISSUE THREAD

**Issue by FrancescoBianchi** [yegor256/thindeck#503]
There are 6+1 classes implementing `com.thindeck.api.Step` interface. None of them implements methods `commit()` and `rollback()`. Consider removing the 2 methods from the interface.
If you predict they can be used in the future you can add them to a new `com.thindeck.api.TransactionalStep` interface that extends `com.thindeck.api.Step` or a completely separate `com.thindeck.api.TransactionalStep` interface

**Comment by yegor256** [comment]
@FrancescoBianchi agree, thanks

**Comment by davvd** [comment]
I'll ask someone to take care of this task soon

**Comment by davvd** [comment]
@marczeeee the task is yours, please go ahead

**Comment by Marczeeee** [comment]
I prefer not to drop functionality so moved the methods to a new `TransactionalStep` interface extending the original `Step`.

**Comment by Marczeeee** [comment]
@FrancescoBianchi Related pull request #511 was merged. I think this issue can be closed.

**Comment by FrancescoBianchi** [comment]
@Marczeeee pull request #511 seems fine to me. I'm closing the issue.

**Comment by davvd** [comment]
@marczeeee Much obliged! I've added **30 mins** to your account in payment "50907823". +30 to your rating, your total score is +240
