### ISSUE TITLE
Change or remove com.thindeck.api.Repos.iterate()

### ISSUE THREAD

**Issue by FrancescoBianchi** [yegor256/thindeck#504]
Consider removing `com.thindeck.api.Repos.iterate()` and make `com.thindeck.api.Repos` implement `Iterable` instead.
If you really want to keep the option to explicitely retrieve an iterable object, change the name of the method from `iterate()` to `getIterator()` or `makeIterator()` because this method does not have the responsibility to iterate over a collection of objects but just to provide an iterable collection instead.

**Comment by yegor256** [comment]
@FrancescoBianchi good point, but... the logic here is that `iterable()` (the name which would be the most appropriate) will expose the internals of the object being returned. There is a convention in Java that an instance of `Iterable` can be used as an array, for iteration:

```
for (Repo repo : repos.iterate()) { ... }
```

If we rename it to `iterable()`, we won't be able to return an array, right? We're not limiting ourselves to the implementation details, but give user the information about **what** we return.

A better name would be `all()`, but in this case we don't show that the result returned is not necessarily in memory.

So, I thought about this `iterate()` name for a long time and find it the most accurate.

**Comment by davvd** [comment]
this task will get someone's attention soon

**Comment by FrancescoBianchi** [comment]
Please have a look at the following sample of working code:
```java
import java.lang.System;
import java.util.Arrays;
import java.util.Iterator;

class BasicIterableExample implements Iterable<String> {

    public static void main(String[] args) {
        for(String name :  new BasicIterableExample()) {
            System.out.println(name);
        }
    }

    @Override
    public Iterator<String> iterator() {
        // this will be the method called if an instance of BasicIterableExample is used in a for...each loop
        return Arrays.asList("Yegor", "David", "Francesco").iterator();
    }
}
```
It seems to me that making a class implementing the Iterable interface you can have the best of both worlds:
* an explicit method to have access to something you can iterate on (if you need it)
* a shorter way to use the object in a for...each loop in a controlled way
Plus you don't have to think about the best name to give the method but you can simply rely on an established, documented and type-safe convention.

Do you think this could work for you?

Also, apologies if my description wasn't clear enough in suggesting this approach.

**Comment by yegor256** [comment]
@FrancescoBianchi yes, that would be great, but `iterator()` doesn't allow us to throw a checked `IOException` :(

**Comment by FrancescoBianchi** [comment]
You are right, this is not a viable solution if you want to throw a checked Exception.

Is this something that you are planning to add in the future? Because unless I'm wrong there is no Exception declared in the Repos interface.

Also, you could reuse the approach followed in DyRepos.add(String)

```
        ...
        } catch (final IOException ex) {
            throw new IllegalStateException(ex);
        }
```

**Comment by davvd** [comment]
@francescobianchi It is "invalid", I am closing it
