### ISSUE TITLE
DyTasksTest.java:81-82: Unignore following test when #492...

### ISSUE THREAD

**Issue by davvd** [yegor256/thindeck#508]
Puzzle `491-fa4a100f` in `src/test/java/com/thindeck/dynamo/DyTasksTest.java:81-82` has to be resolved: Unignore following test when #492 is finished and check the test passes... The puzzle was created by Artem Nakonechny on 21-Jan-2015.

If you have any technical questions, don't ask me, submit new tickets instead

**Comment by davvd** [comment]
@dpisarenko the task is yours plz proceed

**Comment by dpisarenko** [comment]
@davvd Thanks. What does the IMP tag mean?

**Comment by dpisarenko** [comment]
@davvd The puzzle says to unignore the test when https://github.com/yegor256/thindeck/issues/492 iis finished. But it's not - I see that issue #492 is open. Should I still unignore the test?

**Comment by yegor256** [comment]
@dpisarenko "IMP" means "implementor", it's your role in this task

**Comment by yegor256** [comment]
@davvd I think we are blocked by #492 here

**Comment by davvd** [comment]
> @davvd I think we are blocked by #492 here

@yegor256 agreed, we'll wait for #492

**Comment by davvd** [comment]
impediment in issue #492 is closed, we can probably try to continue here

**Comment by dpisarenko** [comment]
@davvd Please find someone to review PR https://github.com/yegor256/thindeck/pull/515 .

**Comment by dpisarenko** [comment]
@davvd PR was merged, please close the issue.

**Comment by dpisarenko** [comment]
@davvd PR was merged, please close the issue.

**Comment by davvd** [comment]
The issue should be closed..

**Comment by davvd** [comment]
@dpisarenko paid, thanks, added **15 mins** to your account, payment `51296189`... +15 to your rating, your total score is [+731](http://www.netbout.com/b/35089?open=rating)
