### ISSUE TITLE
Qulice configuration - no license specified.

### ISSUE THREAD

**Issue by maurezen** [yegor256/thindeck#509]
1. Checkout master branch
2. run `mvn qulice:check -Pqulice`
3. There are multiple `Line does not match expected header line of ' * BSD License'. (HeaderCheck)` messages.

This is a known bug of qulice configuration in parent (jcabi/jcabi-parent#19). Suggested action is upgrading parent version to 0.31.1.

**Comment by davvd** [comment]
@yegor256 dispatch this issue please

**Comment by yegor256** [comment]
@maurezen fixed already, thanks
