### ISSUE TITLE
Extract Log class from Txn

### ISSUE THREAD

**Issue by FrancescoBianchi** [yegor256/thindeck#514]
I would change the return method of `com.thindeck.api.Txn.log()` to a newly defined `Log` class instead of a simple `Iterable`. `Log` class could be a a wrapper around `com.jcabi.log.Logger`. 

Of course `Log` could expose its own `iterate()` method or implement `Iterable` interface (see also issue #504 ).

Also consider moving the following code in `com.thindeck.cockpit.TaskRs.log()` in a method of `Log` class:

`Joiner.on('\n').join(this.base().txn(task).log())` (e.g. a simple `toString()`??)

**Comment by davvd** [comment]
@yegor256 please pay attention to this issue

**Comment by yegor256** [comment]
@FrancescoBianchi these classes are gone, thanks for the ticket anyway
