### ISSUE TITLE
Estimate project size

### ISSUE THREAD

**Issue by davvd** [yegor256/thindeck#519]
There is no estimate in the project yet. We have to create one as explained [here](https://github.com/teamed/est)

**Comment by davvd** [comment]
@carlosmiranda please go ahead with this task, it's yours

**Comment by carlosmiranda** [comment]
Please see pull request #521.

**Comment by carlosmiranda** [comment]
@davvd We're waiting for #521.

**Comment by davvd** [comment]
> @davvd We're waiting for #521.

@carlosmiranda sure, let's wait for #521

**Comment by carlosmiranda** [comment]
@davvd #521 is done, can we close this now?

**Comment by carlosmiranda** [comment]
@davvd @yegor256 I think this task should be closed. It was resolved two weeks ago. What's the delay?

**Comment by yegor256** [comment]
@rultor deploy

**Comment by davvd** [comment]
> @davvd #521 is done, can we close this now?

@carlosmiranda when a fresh estimate is created (in .est file), I will close this ticket

**Comment by davvd** [comment]
we waited for #521, it is closed already

**Comment by carlosmiranda** [comment]
@davvd Please close it already. We created an estimate `est/001.est` in #521.

**Comment by davvd** [comment]
> @davvd Please close it already. We created an estimate `est/001.est` in #521.

@carlosmiranda when a fresh estimate is created (in .est file), I will close this ticket

**Comment by carlosmiranda** [comment]
@davvd Okay just give me more time then.

**Comment by davvd** [comment]
> @davvd Okay just give me more time then.

@carlosmiranda right, take your time and thanks for informing

**Comment by carlosmiranda** [comment]
@davvd Let's close this already, it's been two weeks since the estimate was done!

**Comment by davvd** [comment]
> @davvd Let's close this already, it's been two weeks since the estimate was done!

@carlosmiranda when a fresh estimate is created (in .est file), I will close this ticket

**Comment by carlosmiranda** [comment]
@yegor256 Is there something wrong with the created estimate, or the project setup, that prevents this ticket from being closed?

**Comment by yegor256** [comment]
@rultor deploy

**Comment by yegor256** [comment]
@davvd please add extra 30 mins to @carlosmiranda for his work in #393

**Comment by carlosmiranda** [comment]
@rultor deploy please

**Comment by carlosmiranda** [comment]
@yegor256 Thanks!

**Comment by davvd** [comment]
> @davvd please add extra 30 mins to @carlosmiranda for his work in #393

@yegor256 I've paid 30 mins to @carlosmiranda in transaction `53763359`

**Comment by davvd** [comment]
We are done here, thanks all

**Comment by davvd** [comment]
@carlosmiranda Much obliged! I have added **30 mins** to your account in payment "53802815". +30 added to your rating, current score is: [+4029](http://www.netbout.com/b/35023?open=rating)
