### ISSUE TITLE
DyUserTestITCase.java:45-45: Implement an integration test for...

### ISSUE THREAD

**Issue by davvd** [yegor256/thindeck#520]
Puzzle `410-108e5987` in `src/test/java/com/thindeck/dynamo/DyUserTestITCase.java:45-45` has to be resolved: Implement an integration test for DyUser.repos()... The puzzle was created by Adam Siemion on 13-Feb-2015.

If you have any technical questions, don't ask me, submit new tickets instead

**Comment by davvd** [comment]
@carlosmiranda the task is yours please proceed

**Comment by carlosmiranda** [comment]
@davvd Assign someone else please, I didn't have time to work on this recently.

**Comment by carlosmiranda** [comment]
@davvd Please assign someone else.

**Comment by davvd** [comment]
> @davvd Assign someone else please, I didn't have time to work on this recently.

@carlosmiranda someone else will help in this task, no problem at all

**Comment by davvd** [comment]
> @davvd Please assign someone else.

@carlosmiranda all right, we'll find someone else for this task

**Comment by davvd** [comment]
@yegor256 Closing, thanks all
