### ISSUE TITLE
Upgrade to jcabi-parent 0.32.1

### ISSUE THREAD

**Issue by carlosmiranda** [yegor256/thindeck#524]
Let's upgrade the parent pom to jcabi-parent 0.32.1. This version will keep our dependencies up-to-date. Among other things, it includes jcabi-dynamo `0.18` which incorporates some bug fixes and a more convenient `Conditions` API.

**Comment by carlosmiranda** [comment]
@davvd Please tag this as a valid bug.

**Comment by davvd** [comment]
> @davvd Please tag this as a valid bug.

@carlosmiranda got it, tag `bug` is here

**Comment by davvd** [comment]
@carlosmiranda thank you for reporting this, I added 15 mins to your acc, transaction `53292571`

**Comment by carlosmiranda** [comment]
@davvd can you assign this to me please?

**Comment by davvd** [comment]
> @davvd can you assign this to me please?

@carlosmiranda the task is yours, please proceed

**Comment by davvd** [comment]
> @davvd can you assign this to me please?

@carlosmiranda it's your own task, assigning yourself to it as a performer is a bad practice

**Comment by carlosmiranda** [comment]
@davvd waiting for #527 here.

**Comment by davvd** [comment]
> @davvd waiting for #527 here.

@carlosmiranda got it, let's wait for #527

**Comment by carlosmiranda** [comment]
Done in #527.

**Comment by davvd** [comment]
@carlosmiranda thank you, added **30 mins** to your acc, payment num is `53772595`... +30 to your rating, your total score is [+3893](http://www.netbout.com/b/35023?open=rating)
