### ISSUE TITLE
DyRepos.add() does not include a message when throwing IllegalArgumentException

### ISSUE THREAD

**Issue by carlosmiranda** [yegor256/thindeck#529]
At the moment, `DyRepos.add()` will throw an `IllegalArgumentException` when it finds that the supplied repo already exists. However, it does not include any message in the exception that it throws, which does not help in finding out what went wrong.

We should add an exception message that specifically states what happened, something similar to:

> Repo [repo name] already exists

**Comment by carlosmiranda** [comment]
@davvd This is a valid bug.

**Comment by davvd** [comment]
> @davvd This is a valid bug.

@carlosmiranda OK, I labeled it as `bug`

**Comment by davvd** [comment]
@carlosmiranda thanks for reporting! I topped your account for 15 mins, transaction 53764880

**Comment by yegor256** [comment]
@carlosmiranda fixed in acfa045

**Comment by carlosmiranda** [comment]
@yegor256 Thanks!
