### ISSUE TITLE
migrate to Takes

### ISSUE THREAD

**Issue by yegor256** [yegor256/thindeck#540]
Let's migrate to Takes framework

**Comment by davvd** [comment]
@yegor256 the task is yours (budget is 30 mins)

**Comment by davvd** [comment]
@yegor256 thank you for the ticket reported, I topped your account for 15 mins, transaction `000-c940ae76`

**Comment by yegor256** [comment]
@rultor release, tag is `0.5`

**Comment by yegor256** [comment]
@rultor release, tag is `0.5`

**Comment by yegor256** [comment]
@rultor release, tag is `0.5`

**Comment by yegor256** [comment]
@rultor release, tag is `0.5`

**Comment by yegor256** [comment]
@rultor release, tag is `0.5`

**Comment by davvd** [comment]
@yegor256 thanks, I just added **45 mins** to your account, payment `000-7bf5a7a1`, 32 hours and 9 mins spent. the bonus for fast delivery (m=1929). added +45 to your rating, now it is equal to [+7081](http://www.netbout.com/b/35008?open=rating)
