### ISSUE TITLE
live hosting doesn't work

### ISSUE THREAD

**Issue by yegor256** [yegor256/thindeck#541]

**Comment by davvd** [comment]
@yegor256 I tagged this as "bug"

**Comment by davvd** [comment]
@yegor256 thanks for the report, I topped your acc for 15 mins, payment ID `000-269ebc9c`

**Comment by yegor256** [comment]
@davvd works fine

**Comment by davvd** [comment]
> @davvd works fine

@yegor256 OK thanks
