### ISSUE TITLE
decks instead of repos

### ISSUE THREAD

**Issue by yegor256** [yegor256/thindeck#542]

**Comment by davvd** [comment]
@yegor256 the task is yours (budget is 30 mins)

**Comment by davvd** [comment]
@yegor256 thanks for the report, I topped your acc for 15 mins, payment ID `000-8ea33264`

**Comment by yegor256** [comment]
@davvd fixed

**Comment by yegor256** [comment]
@rultor deploy

**Comment by davvd** [comment]
@yegor256 Thanks so much! Your account was topped up for **30 mins** (transaction ID is `000-9cdefa62`, the task took 648 hours and 7 mins). added +30 to your rating, now it is equal to [+10679](http://www.netbout.com/b/35008?open=rating)
