### ISSUE TITLE
deploy to Dokku

### ISSUE THREAD

**Issue by yegor256** [yegor256/thindeck#557]
Let's deploy

**Comment by yegor256** [comment]
@rultor release, tag is `0.7.2`

**Comment by yegor256** [comment]
@rultor release, tag is `0.7.2`

**Comment by yegor256** [comment]
@rultor release, tag is `0.7.2`

**Comment by 0crat** [comment]
Job `gh:yegor256/thindeck#557` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
